apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: goapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: goapp 
    spec:
      containers:
        - name: goapp 
          image: ronacr.azurecr.io/goapp
          ports:
          - containerPort: 80